// <auto-generated />
using DeveloperPortfolio.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeveloperPortfolio.Api.Migrations
{
    [DbContext(typeof(DeveloperPortfolioDbContext))]
    partial class DeveloperPortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeveloperPortfolio.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "fa-solid fa-globe",
                            Name = "Web Projects"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "fa-solid fa-gamepad",
                            Name = "Games"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "fa-solid fa-cube",
                            Name = "Blender Projects"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "fa-solid fa-book",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "fa-solid fa-chalkboard-user",
                            Name = "Online Courses"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "fa-solid fa-newspaper",
                            Name = "Magazines"
                        });
                });

            modelBuilder.Entity("DeveloperPortfolio.Api.Entities.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "https://github.com/prospero-apps/ExtremeVacation",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            Destination = "https://happy-water-095a43b10.3.azurestaticapps.net",
                            DisplayText = "Live",
                            Icon = "fa-solid fa-rocket",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Destination = "https://github.com/prospero-apps/forest-monsters",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 4,
                            Destination = "https://youtu.be/i7xyMbhdg_8",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 5,
                            Destination = "https://prosperocoder.com/posts/unity/forest-monsters-a-2d-platformer-game-made-with-unity",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            Destination = "https://prosperocoder.itch.io/forest-monsters",
                            DisplayText = "Download",
                            Icon = "fa-solid fa-download",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            Destination = "https://github.com/prospero-apps/slugrace",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 8,
                            Destination = "https://youtu.be/z24eIFsbEl8",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 9,
                            Destination = "https://prosperocoder.com/blog/posts/kivy",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            Destination = "https://github.com/prospero-apps/cv-project",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 11,
                            Destination = "https://prospero-apps.github.io/cv-project",
                            DisplayText = "Live",
                            Icon = "fa-solid fa-rocket",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 12,
                            Destination = "https://github.com/prospero-apps/waldo",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 13,
                            Destination = "https://prospero-apps.github.io/waldo/",
                            DisplayText = "Live",
                            Icon = "fa-solid fa-rocket",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 14,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 6
                        },
                        new
                        {
                            Id = 15,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 7
                        },
                        new
                        {
                            Id = 16,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 17,
                            Destination = "https://prosperocoder.com/posts/blender/bacteria-model-under-electron-microscope",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 18,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 9
                        },
                        new
                        {
                            Id = 19,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 10
                        },
                        new
                        {
                            Id = 20,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 21,
                            Destination = "https://youtu.be/crGOEzZ2V6Y",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 22,
                            Destination = "https://prosperocoder.com/posts/blender/tangled-wire-ball-with-uv-sphere",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 11
                        },
                        new
                        {
                            Id = 23,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files/Town%20Houses",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 24,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files/Treasure%20Chest",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 13
                        },
                        new
                        {
                            Id = 25,
                            Destination = "https://prosperocoder.com/posts/blender/treasure-chest-model",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 13
                        },
                        new
                        {
                            Id = 26,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 14
                        },
                        new
                        {
                            Id = 27,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 28,
                            Destination = "https://youtu.be/SPVJAwIuqJs",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 29,
                            Destination = "https://prosperocoder.com/posts/blender/tunnel-animation-follow-path-constraint",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 15
                        },
                        new
                        {
                            Id = 30,
                            Destination = "https://github.com/prospero-apps/blender/tree/master/blend%20files",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 16
                        },
                        new
                        {
                            Id = 31,
                            Destination = "https://prosperocoder.com/posts/blender/alien-creature-animation",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 16
                        },
                        new
                        {
                            Id = 32,
                            Destination = "https://github.com/prospero-apps/python/tree/master/GUI%20Programming%20with%20Python%20and%20Kivy%20BOOK",
                            DisplayText = "Github",
                            Icon = "devicon-github-original",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 33,
                            Destination = "https://www.amazon.com/Programming-Python-Kivy-Kamil-Pakula/dp/B09M9CYRCX/ref=asc_df_B09M9CYRCX/?tag=hyprod-20&linkCode=df0&hvadid=564675582183&hvpos=&hvnetw=g&hvrand=10679525743492153029&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1014434&hvtargid=pla-1595705564143&psc=1",
                            DisplayText = "Amazon",
                            Icon = "fa-brands fa-amazon",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 34,
                            Destination = "https://prosperocoder.com/product/gui-programming-with-python-and-kivy-e-book",
                            DisplayText = "Prospero Coder Store",
                            Icon = "fa-solid fa-cart-shopping",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 35,
                            Destination = "https://youtu.be/3W8zDYMBoDk",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 36,
                            Destination = "https://prosperocoder.com/posts/kivy/my-gui-programming-with-python-and-kivy-book",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 17
                        },
                        new
                        {
                            Id = 37,
                            Destination = "https://www.amazon.com/-/es/Kamil-Pakula/dp/B09RM5XFLS",
                            DisplayText = "Amazon",
                            Icon = "fa-brands fa-amazon",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 38,
                            Destination = "https://prosperoenglish.com/product/learn-over-400-phrasal-verbs-the-fun-way",
                            DisplayText = "Prospero English Store",
                            Icon = "fa-solid fa-cart-shopping",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 39,
                            Destination = "https://youtu.be/yCFe0nKw8JM",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 40,
                            Destination = "https://prosperoenglish.com/posts/my-learn-over-400-phrasal-verbs-book",
                            DisplayText = "Prospero English blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 18
                        },
                        new
                        {
                            Id = 41,
                            Destination = "https://www.udemy.com/course/python-jumpstart-course",
                            DisplayText = "Udemy",
                            Icon = "fa-solid fa-globe",
                            ProjectId = 19
                        },
                        new
                        {
                            Id = 42,
                            Destination = "https://www.skillshare.com/en/classes/Python-in-Science-%E2%80%93-Introduction-to-numpy/1418900066/projects",
                            DisplayText = "Skillshare",
                            Icon = "fa-solid fa-globe",
                            ProjectId = 20
                        },
                        new
                        {
                            Id = 43,
                            Destination = "https://www.udemy.com/course/advanced-english-learn-over-400-phrasal-verbs",
                            DisplayText = "Udemy",
                            Icon = "fa-solid fa-globe",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 44,
                            Destination = "https://www.skillshare.com/en/classes/Advanced-English-%E2%80%93-Learn-Over-400-Phrasal-Verbs/1050280779/projects",
                            DisplayText = "Skillshare",
                            Icon = "fa-solid fa-globe",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 45,
                            Destination = "https://youtu.be/KF_OqSmU554",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 46,
                            Destination = "https://prosperoenglish.com/posts/my-learn-over-400-phrasal-verbs-the-fun-way-course",
                            DisplayText = "Prospero English blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 21
                        },
                        new
                        {
                            Id = 47,
                            Destination = "https://www.amazon.com/Your-Panda3D-Magazine-Kamil-Pakula-ebook/dp/B09SR785WV",
                            DisplayText = "Amazon",
                            Icon = "fa-brands fa-amazon",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 48,
                            Destination = "https://prosperocoder.com/product/your-panda3d-magazine-1-1-2022",
                            DisplayText = "Prospero Coder Store",
                            Icon = "fa-solid fa-cart-shopping",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 49,
                            Destination = "https://youtu.be/N9_rrQXIuuo",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 50,
                            Destination = "https://prosperocoder.com/posts/your-panda3d-magazine-issue-1-2022-1",
                            DisplayText = "Prospero Coder blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 22
                        },
                        new
                        {
                            Id = 51,
                            Destination = "https://www.amazon.com/Your-American-English-Magazine-2022-ebook/dp/B09SQCZVF1",
                            DisplayText = "Amazon",
                            Icon = "fa-brands fa-amazon",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 52,
                            Destination = "https://prosperoenglish.com/product/your-american-english-magazine-1-1-2022",
                            DisplayText = "Prospero English Store",
                            Icon = "fa-solid fa-cart-shopping",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 53,
                            Destination = "https://youtu.be/XGlzwmBcsyY",
                            DisplayText = "YouTube",
                            Icon = "fa-brands fa-youtube",
                            ProjectId = 23
                        },
                        new
                        {
                            Id = 54,
                            Destination = "https://prosperoenglish.com/posts/your-american-english-magazine-issue-1-2022-1",
                            DisplayText = "Prospero English blog",
                            Icon = "fa-solid fa-blog",
                            ProjectId = 23
                        });
                });

            modelBuilder.Entity("DeveloperPortfolio.Api.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A portal that I made just for fun. You can use it to book your extreme vacation like in a burning city or sharing a den with a bear. The project is hosted in Azure, the backend was created using the ASP.NET Core Web API template and the frontend was made with Blazor WebAssembly. The data is stored in a SQL Server database. I used Entity Framework Core as the ORM.",
                            ImageUrl = "images/extreme-vacation.png",
                            Name = "Extreme Vacation"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "A 2D game made with Unity with C# scripting. Your task is to save the enchanted forest from a bad sorcerer. You have to kill lots of monsters on your way. This is a typical platformer game. You jump from platform to platform, collect items, shoot monsters, avoid bombs and poison, move toward the door to the next level. Some of the platforms can move, which makes the game more difficult.",
                            ImageUrl = "images/Forest Monsters.png",
                            Name = "Forest Monsters"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "A 2D game made with Python and Kivy. It can be played by up to four players. Each player places a bet on one of four racing slugs and they either win or lose money. The game is over when there's only one player left with any money, but you can set a different ending condition in the settings screen too, like after a given number of races or after a set period of time.",
                            ImageUrl = "images/Slugrace.png",
                            Name = "Slugrace"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "This is my first React project. In this app you can fill in a form with your personal information (like name, address, experience and education) to create a CV. You can also upload a photo. There's also a live preview of the CV, so whatever you type in the form is instantly visualized in the preview on the right.",
                            ImageUrl = "images/cv-project.png",
                            Name = "CV Project"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "This is a simple version of the popular Where Is Waldo game where you have to find Waldo and some other characters in the image. This isn't easy because there are a great number of characters in the image. If you find all three characters in an image, just try another image. There are three images to choose from. This project uses Firebase as the backend.",
                            ImageUrl = "images/waldo.png",
                            Name = "Waldo"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Abstract artwork, pretty useless, just nice for the eye. You can open the blend file available on Github and tweak it to your heart's content. The options are countless.",
                            ImageUrl = "images/Abstract Artwork.jpg",
                            Name = "Abstract Artwork"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "A low-poly cellar model with simple texturing. You can import it in Unity or any other game engine and use as an environment for your project.",
                            ImageUrl = "images/Arched Cellar.jpg",
                            Name = "Arched Cellar"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Bacteria as seen under an electron microscope. When you use an electron microscope, the object you watch is no longer alive, so the bacteria is not going to be animated. I also have a blog post where you can see how this model was built.",
                            ImageUrl = "images/Bacteria.png",
                            Name = "Bacteria"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "A couple high-poly rigged characters I created in Blender. They are animated, but as they are high-poly, they don't actually lend themselves very well to being used in a game.",
                            ImageUrl = "images/Characters.png",
                            Name = "Funny Characters"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "A gravestone with some inscriptions on it. It's a high-poly model, so it's not well suited for being used in a game, although it might be used in one as a static game object.",
                            ImageUrl = "images/Gravestone.png",
                            Name = "Gravestone"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "A simple animation, in which a ball of tangled wire rotates around its Z axis and then moves toward the camera along the Y axis until the camera is inside the ball.",
                            ImageUrl = "images/Tangled Wire Ball.jpg",
                            Name = "Tangled Wire Ball Animation"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Five low-poly models of town houses, ready to export to Unity or any other game engine. The models are fully textured.",
                            ImageUrl = "images/Town Houses.png",
                            Name = "Town Houses"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "A model of a chest with an open lid and light coming out of it. If you want to model the chest along with me, just follow the step-by-step instructions in my blog post.",
                            ImageUrl = "images/Treasure Chest.jpg",
                            Name = "Treasure Chest"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "A tropical island with dense vegetation and the sea. The model is high-poly, so not very well suited for being used in a game. It consists of numerous smaller models of plants and stones that I created before.",
                            ImageUrl = "images/Tropical Island.jpg",
                            Name = "Tropical Island"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "A simple first-person-perspective animated journey through a tunnel - a tunnel animation using the follow path constraint, in which the camera will move along a path inside a tunnel.",
                            ImageUrl = "images/Tunnel.jpg",
                            Name = "Tunnel Animation"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "A simple animation of a worm winding its body. You can read my blog post with step-by-step instructions to first model and then animate along the worm.",
                            ImageUrl = "images/Worm.jpg",
                            Name = "Alien Creature Animation"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            Description = "This is a book for Python developers who want to create GUI apps using this language. One option is to use the Kivy library. In the book a game project is created from scratch.",
                            ImageUrl = "images/Kivy Book.png",
                            Name = "GUI Programming with Python and Kivy"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "In this book you will learn over 400 hundred phrasal verbs. Phrasal verbs are verbs that consist of two parts, the actual verb and a particle, like 'stand up', 'get off' or 'turn down', to mention just a few.",
                            ImageUrl = "images/Phrasal Verbs Book.png",
                            Name = "Learn Over 400 Phrasal Verbs the Fun Way"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            Description = "A Python course for absolute beginners. Lots of examples, exercises and projects for you to do. Includes the object-oriented programming paradigm.",
                            ImageUrl = "images/Python Jumpstart Course.png",
                            Name = "Python Jumpstart Course"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            Description = "This is a beginner course for Python developers who want to start using Python in science. numpy is the most basic library you should definitely start with.",
                            ImageUrl = "images/numpy.png",
                            Name = "Python in Science - Introduction to numpy"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            Description = "In this course you will learn over 400 phrasal verbs. Phrasal verbs are very popular especially in everyday colloquial language and using them makes you sound more like a native.",
                            ImageUrl = "images/Phrasal Verbs Course.png",
                            Name = "Advanced English - Learn Over 400 Phrasal Verbs"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "This is the first (and so far only) issue of a magazine focused on game development with Python and the Panda3D game engine. There's also quite a lot stuff related to 3D modeling with Blender.",
                            ImageUrl = "images/Your Panda3D Magazine.png",
                            Name = "Your Panda3D Magazine"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Description = "This is the first issue of Your American English Magazine. There's quite a lot of stuff in it for you that you can use to improve your English, both grammar and vocabulary. Plus some American culture.",
                            ImageUrl = "images/Your American English Magazine.png",
                            Name = "Your American English Magazine"
                        });
                });

            modelBuilder.Entity("DeveloperPortfolio.Api.Entities.ProjectTechRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TechId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectTechRelations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 1,
                            TechId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 1,
                            TechId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 1,
                            TechId = 4
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 1,
                            TechId = 5
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 1,
                            TechId = 12
                        },
                        new
                        {
                            Id = 6,
                            ProjectId = 1,
                            TechId = 11
                        },
                        new
                        {
                            Id = 7,
                            ProjectId = 1,
                            TechId = 10
                        },
                        new
                        {
                            Id = 8,
                            ProjectId = 2,
                            TechId = 1
                        },
                        new
                        {
                            Id = 9,
                            ProjectId = 2,
                            TechId = 3
                        },
                        new
                        {
                            Id = 10,
                            ProjectId = 3,
                            TechId = 8
                        },
                        new
                        {
                            Id = 11,
                            ProjectId = 4,
                            TechId = 4
                        },
                        new
                        {
                            Id = 12,
                            ProjectId = 4,
                            TechId = 5
                        },
                        new
                        {
                            Id = 13,
                            ProjectId = 4,
                            TechId = 6
                        },
                        new
                        {
                            Id = 14,
                            ProjectId = 4,
                            TechId = 7
                        },
                        new
                        {
                            Id = 15,
                            ProjectId = 5,
                            TechId = 4
                        },
                        new
                        {
                            Id = 16,
                            ProjectId = 5,
                            TechId = 5
                        },
                        new
                        {
                            Id = 17,
                            ProjectId = 5,
                            TechId = 6
                        },
                        new
                        {
                            Id = 18,
                            ProjectId = 5,
                            TechId = 7
                        },
                        new
                        {
                            Id = 19,
                            ProjectId = 6,
                            TechId = 9
                        },
                        new
                        {
                            Id = 20,
                            ProjectId = 7,
                            TechId = 9
                        },
                        new
                        {
                            Id = 21,
                            ProjectId = 8,
                            TechId = 9
                        },
                        new
                        {
                            Id = 22,
                            ProjectId = 9,
                            TechId = 9
                        },
                        new
                        {
                            Id = 23,
                            ProjectId = 10,
                            TechId = 9
                        },
                        new
                        {
                            Id = 24,
                            ProjectId = 11,
                            TechId = 9
                        },
                        new
                        {
                            Id = 25,
                            ProjectId = 12,
                            TechId = 9
                        },
                        new
                        {
                            Id = 26,
                            ProjectId = 13,
                            TechId = 9
                        },
                        new
                        {
                            Id = 27,
                            ProjectId = 14,
                            TechId = 9
                        },
                        new
                        {
                            Id = 28,
                            ProjectId = 15,
                            TechId = 9
                        },
                        new
                        {
                            Id = 29,
                            ProjectId = 16,
                            TechId = 9
                        },
                        new
                        {
                            Id = 30,
                            ProjectId = 17,
                            TechId = 8
                        },
                        new
                        {
                            Id = 31,
                            ProjectId = 18,
                            TechId = 14
                        },
                        new
                        {
                            Id = 32,
                            ProjectId = 19,
                            TechId = 8
                        },
                        new
                        {
                            Id = 33,
                            ProjectId = 20,
                            TechId = 14
                        },
                        new
                        {
                            Id = 34,
                            ProjectId = 21,
                            TechId = 8
                        },
                        new
                        {
                            Id = 35,
                            ProjectId = 22,
                            TechId = 8
                        },
                        new
                        {
                            Id = 36,
                            ProjectId = 23,
                            TechId = 14
                        });
                });

            modelBuilder.Entity("DeveloperPortfolio.Api.Entities.Tech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Techs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "devicon-csharp-plain",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "devicon-dotnetcore-plain",
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "devicon-unity-original",
                            Name = "Unity"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "devicon-html5-plain",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "devicon-css3-plain",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "devicon-javascript-plain",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "devicon-react-original",
                            Name = "React"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "devicon-python-plain",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "devicon-blender-original",
                            Name = "Blender"
                        },
                        new
                        {
                            Id = 10,
                            Icon = "devicon-azure-plain",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 11,
                            Icon = "devicon-microsoftsqlserver-plain",
                            Name = "Microsoft SQL Server"
                        },
                        new
                        {
                            Id = 12,
                            Icon = "devicon-bootstrap-plain",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 13,
                            Icon = "devicon-sass-original",
                            Name = "Sass"
                        },
                        new
                        {
                            Id = 14,
                            Icon = "fa-solid fa-flag-usa",
                            Name = "english"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
